maintainer        "CanaryTek"
name              "modularit"
maintainer_email  "kuko@canarytek.com"
license           "GPL3"
description       "Installs/Configures modularit"
long_description  IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version           "0.1.5"
depends           "rasca","~> 0.1.3"
depends           "yum"
depends           "openssh"
depends           "users"
depends           "sudo"
depends           "ntp"
depends           "chef-client"
depends           "hostsfile"
depends           "modularit-backup"
